source 'http://rubygems.org'

# { Middleman
gem "middleman", "~>3.2.0"
gem "middleman-livereload", "~> 3.1.0"
gem "middleman-favicon-maker", "~> 3.3"
gem "middleman-smusher", "~> 3.0.0"
# }

# { Styles
gem "compass"
gem "zurb-foundation"
# }
